name: Docker Build and Push

on:
  push:
    branches:
      - production  # Change this to your default branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAME: nobody9512/kub-laravel
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker buildx build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
          docker push $IMAGE_NAME:$IMAGE_TAG
